services:
  postgres_db:
    restart: unless-stopped
    # image: postgres:16
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/postgres
    volumes:
      - /postgres_db_data:/var/lib/postgresql/data
    command: -p 5432
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env-prd
    expose: 
      - ${DATABASE_PORT}
    ports:
      - "5433:5432"
  celery_redis:
    restart: unless-stopped
    image: redis:latest
    volumes:
      - celery_redis_data:/data
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    command: >
      sh -c "
        MILLISECOND_TIMESTAMP=$$(date +%s%3N);
        NODENAME=worker_$$MILLISECOND_TIMESTAMP@$$(hostname -f);
        celery -A data_celery.main:celery_app worker --loglevel=info --pool=eventlet -n $$NODENAME
      "
    depends_on:
      - celery_redis
  api_server:
    build: .
    env_file:
      - .env-prd
    volumes:
      # - .:/dataflow
      - ${DATA_DIR}:${DATA_DIR}
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - celery_worker
    # command: ["uvicorn", "data_server.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_db:
  celery_redis_data:
